[package]
name = "ed25519_sigs"
version = "0.1.0"
authors = ["Nicolas Marshall <marshall.nicolas@gmail.com>"]
edition = "2018"

[lib]
crate-type =["cdylib"]

[dependencies]
rust-crypto-wasm = "=0.3.1"
wasm-bindgen = "=0.2"
base64 = "=0.11.0"
js-sys = "=0.3.35"
bip39 = "0.6.0-beta.1"
console_error_panic_hook = "0.1.6"
blake2 = "0.8"
ed25519-dalek = { version = "1.0.0-pre.3", features = ["nightly"] }
