[package]
name = "ed25519_sigs"
version = "0.1.0"
authors = ["Nicolas Marshall <marshall.nicolas@gmail.com>"]
edition = "2018"

[lib]
crate-type =["cdylib"]

[dependencies]
# ed25519-dalek = "1.0.0-pre.3"
# rand = "^0.7"
# rand_chacha = "0.2.1"
# rand_core = "*"
rust-crypto-wasm = "=0.3.1"
wasm-bindgen = "0.2"